### ISSUE TITLE
New revision

### ISSUE THREAD

**Issue by tomreeves2** [UMISolutions/LaserMarking2#11]
Right now we save edits to our programs out as the PN and the revision. So if we change the desc on a generic template the program can be saved at 81234_0. Then, when that part is revised, it will be 81234_1 and when the user selects it to build it, there will not be a custom program for it yet, So, what we end up with is them having to remake their changes.

I wonder if it is worth having a old revision check for any parts with a rev other than 0? This way the program can say rev 0 exists for this part do you want to build off of that? We just need to be careful as the revision might be to the description. 

Also, what is in place now for revision checks? It will check if a newer rev of the part exists in the PDM when a part is selected from the orders list, correct?

**Comment by akaegiMultiFlow** [comment]
Loop backwards from rev to 0
