### ISSUE TITLE
Selecting parts within an assembly

### ISSUE THREAD

**Issue by tomreeves2** [UMISolutions/LaserMarking2#5]
- All tube kits in the refresh orders tab seem to show me P176 tubes. I recall you mentioned that the P176 tubes do not work because there are no drawings for the individual tubes. Can you try and make the error messages show this as more clear? If a drawing is not found, state that it needs to be created or something?
I just tested and if i click on TK234-01, it tells me there was an error selecting from the projects folder. Then, it displays all of the P176 parts. clicking on one of these states it is not found in the 80000 folder. Is that where this is searching? Or is it just the error message?

**Comment by ArshPatel1** [comment]
Should be fixed now. If a part number is not found it will give a better error message and once a tube kit is clicked it will display the correct parts.
